const shipData = [
    {
        Symbol: "FBLAIR",
        Model: "AIRBIKE",
        Manufacturer: "Fimbul",
        Spec: "Racer",
        Class: 1,
        "Cargo Capacity": 249,
        "Fuel Capacity": 450,
        "Ammo Capacity": 104,
        "Food/s (Mining)": 0.021,
        "Ammo/s (Mining)": 0.019,
        "Mining Rate (Resource/s)": 0.374,
        "Subwarp Speed (AU/s)": 0.0084,
        "Warp Speed (AU/s)": 0.1,
        "Max Warp Distance": 1.75,
        "Base Warp Cooldown": 60,
        "Fuel/AU Warped": 18.76,
        "Fuel/AU Subwarp": 14.43,
        "Fuel (Asteroid Exit)": 5,
        "Scan Cooldown (sec)": 58,
        "Active Crew (For Crafting)": 1,
        "Respawn Time (s)": 60,
        "Toolkits/Scan": 1,
        "Crew (For Food Cons)": 1,
    },
    {
        Symbol: "OPALJ",
        Model: "JET",
        Manufacturer: "Opal",
        Spec: "Racer",
        Class: 1,
        "Cargo Capacity": 249,
        "Fuel Capacity": 450,
        "Ammo Capacity": 104,
        "Food/s (Mining)": 0.021,
        "Ammo/s (Mining)": 0.019,
        "Mining Rate (Resource/s)": 0.374,
        "Subwarp Speed (AU/s)": 0.0081,
        "Warp Speed (AU/s)": 0.1,
        "Max Warp Distance": 1.95,
        "Base Warp Cooldown": 60,
        "Fuel/AU Warped": 18.05,
        "Fuel/AU Subwarp": 13.89,
        "Fuel (Asteroid Exit)": 5,
        "Scan Cooldown (sec)": 60,
        "Active Crew (For Crafting)": 1,
        "Respawn Time (s)": 60,
        "Toolkits/Scan": 1,
        "Crew (For Food Cons)": 1,
    },
    {
        Symbol: "VZUSSO",
        Model: "SOLOS",
        Manufacturer: "VZUS",
        Spec: "Racer",
        Class: 1,
        "Cargo Capacity": 249,
        "Fuel Capacity": 450,
        "Ammo Capacity": 104,
        "Food/s (Mining)": 0.021,
        "Ammo/s (Mining)": 0.019,
        "Mining Rate (Resource/s)": 0.374,
        "Subwarp Speed (AU/s)": 0.0076,
        "Warp Speed (AU/s)": 0.1,
        "Max Warp Distance": 1.8,
        "Base Warp Cooldown": 60,
        "Fuel/AU Warped": 18.29,
        "Fuel/AU Subwarp": 14.07,
        "Fuel (Asteroid Exit)": 5,
        "Scan Cooldown (sec)": 56,
        "Active Crew (For Crafting)": 1,
        "Respawn Time (s)": 60,
        "Toolkits/Scan": 1,
        "Crew (For Food Cons)": 1,
    },
    {
        Symbol: "FBLEUN",
        Model: "UNIBOMBA",
        Manufacturer: "Fimbul ECOS",
        Spec: "Bomber",
        Class: 1,
        "Cargo Capacity": 274,
        "Fuel Capacity": 267,
        "Ammo Capacity": 336,
        "Food/s (Mining)": 0.021,
        "Ammo/s (Mining)": 0.023,
        "Mining Rate (Resource/s)": 0.464,
        "Subwarp Speed (AU/s)": 0.0052,
        "Warp Speed (AU/s)": 0.1,
        "Max Warp Distance": 1.9,
        "Base Warp Cooldown": 60,
        "Fuel/AU Warped": 15.48,
        "Fuel/AU Subwarp": 11.9,
        "Fuel (Asteroid Exit)": 4,
        "Scan Cooldown (sec)": 42,
        "Active Crew (For Crafting)": 1,
        "Respawn Time (s)": 60,
        "Toolkits/Scan": 1,
        "Crew (For Food Cons)": 1,
    },
    {
        Symbol: "PX4",
        Model: "X4",
        Manufacturer: "Pearce",
        Spec: "Fighter",
        Class: 1,
        "Cargo Capacity": 389,
        "Fuel Capacity": 267,
        "Ammo Capacity": 228,
        "Food/s (Mining)": 0.021,
        "Ammo/s (Mining)": 0.023,
        "Mining Rate (Resource/s)": 0.458,
        "Subwarp Speed (AU/s)": 0.007,
        "Warp Speed (AU/s)": 0.1,
        "Max Warp Distance": 2,
        "Base Warp Cooldown": 60,
        "Fuel/AU Warped": 15.48,
        "Fuel/AU Subwarp": 11.9,
        "Fuel (Asteroid Exit)": 4,
        "Scan Cooldown (sec)": 53,
        "Active Crew (For Crafting)": 1,
        "Respawn Time (s)": 60,
        "Toolkits/Scan": 1,
        "Crew (For Food Cons)": 1,
    },
    {
        Symbol: "OPALJJ",
        Model: "JETJET",
        Manufacturer: "Opal",
        Spec: "Racer",
        Class: 2,
        "Cargo Capacity": 863,
        "Fuel Capacity": 1797,
        "Ammo Capacity": 359,
        "Food/s (Mining)": 0.041,
        "Ammo/s (Mining)": 0.058,
        "Mining Rate (Resource/s)": 1.157,
        "Subwarp Speed (AU/s)": 0.0081,
        "Warp Speed (AU/s)": 0.1,
        "Max Warp Distance": 3.9,
        "Base Warp Cooldown": 120,
        "Fuel/AU Warped": 55.82,
        "Fuel/AU Subwarp": 42.94,
        "Fuel (Asteroid Exit)": 15,
        "Scan Cooldown (sec)": 53,
        "Active Crew (For Crafting)": 2,
        "Respawn Time (s)": 80,
        "Toolkits/Scan": 2,
        "Crew (For Food Cons)": 2,
    },
    {
        Symbol: "FBLLOW",
        Model: "LOWBIE",
        Manufacturer: "Fimbul",
        Spec: "Transport",
        Class: 2,
        "Cargo Capacity": 1965,
        "Fuel Capacity": 1390,
        "Ammo Capacity": 288,
        "Food/s (Mining)": 0.041,
        "Ammo/s (Mining)": 0.053,
        "Mining Rate (Resource/s)": 1.061,
        "Subwarp Speed (AU/s)": 0.0061,
        "Warp Speed (AU/s)": 0.1,
        "Max Warp Distance": 4.1,
        "Base Warp Cooldown": 120,
        "Fuel/AU Warped": 40.6,
        "Fuel/AU Subwarp": 31.23,
        "Fuel (Asteroid Exit)": 11,
        "Scan Cooldown (sec)": 58,
        "Active Crew (For Crafting)": 2,
        "Respawn Time (s)": 80,
        "Toolkits/Scan": 2,
        "Crew (For Food Cons)": 2,
    },
    {
        Symbol: "PX5",
        Model: "X5",
        Manufacturer: "Pearce",
        Spec: "Fighter",
        Class: 2,
        "Cargo Capacity": 1107,
        "Fuel Capacity": 923,
        "Ammo Capacity": 1270,
        "Food/s (Mining)": 0.041,
        "Ammo/s (Mining)": 0.071,
        "Mining Rate (Resource/s)": 1.415,
        "Subwarp Speed (AU/s)": 0.0064,
        "Warp Speed (AU/s)": 0.1,
        "Max Warp Distance": 3.8,
        "Base Warp Cooldown": 120,
        "Fuel/AU Warped": 47.85,
        "Fuel/AU Subwarp": 36.81,
        "Fuel (Asteroid Exit)": 13,
        "Scan Cooldown (sec)": 56,
        "Active Crew (For Crafting)": 2,
        "Respawn Time (s)": 80,
        "Toolkits/Scan": 2,
        "Crew (For Food Cons)": 2,
    },
    {
        Symbol: "OGKANR",
        Model: "NIRUCH",
        Manufacturer: "Ogrika",
        Spec: "Transport",
        Class: 2,
        "Cargo Capacity": 1965,
        "Fuel Capacity": 1390,
        "Ammo Capacity": 288,
        "Food/s (Mining)": 0.041,
        "Ammo/s (Mining)": 0.053,
        "Mining Rate (Resource/s)": 1.061,
        "Subwarp Speed (AU/s)": 0.0064,
        "Warp Speed (AU/s)": 0.1,
        "Max Warp Distance": 4,
        "Base Warp Cooldown": 120,
        "Fuel/AU Warped": 37.7,
        "Fuel/AU Subwarp": 29,
        "Fuel (Asteroid Exit)": 10,
        "Scan Cooldown (sec)": 56,
        "Active Crew (For Crafting)": 2,
        "Respawn Time (s)": 80,
        "Toolkits/Scan": 2,
        "Crew (For Food Cons)": 2,
    },
    {
        Symbol: "CALSCD",
        Model: "SCUD",
        Manufacturer: "Calico",
        Spec: "Racer",
        Class: 2,
        "Cargo Capacity": 863,
        "Fuel Capacity": 1797,
        "Ammo Capacity": 359,
        "Food/s (Mining)": 0.021,
        "Ammo/s (Mining)": 0.058,
        "Mining Rate (Resource/s)": 1.157,
        "Subwarp Speed (AU/s)": 0.0078,
        "Warp Speed (AU/s)": 0.1,
        "Max Warp Distance": 3.4,
        "Base Warp Cooldown": 120,
        "Fuel/AU Warped": 54.37,
        "Fuel/AU Subwarp": 41.82,
        "Fuel (Asteroid Exit)": 15,
        "Scan Cooldown (sec)": 54,
        "Active Crew (For Crafting)": 1,
        "Respawn Time (s)": 80,
        "Toolkits/Scan": 2,
        "Crew (For Food Cons)": 1,
    },
    {
        Symbol: "CALMAX",
        Model: "MAXHOG",
        Manufacturer: "Calico",
        Spec: "Transport",
        Class: 2,
        "Cargo Capacity": 2205,
        "Fuel Capacity": 1150,
        "Ammo Capacity": 288,
        "Food/s (Mining)": 0.041,
        "Ammo/s (Mining)": 0.053,
        "Mining Rate (Resource/s)": 1.061,
        "Subwarp Speed (AU/s)": 0.0067,
        "Warp Speed (AU/s)": 0.1,
        "Max Warp Distance": 4.2,
        "Base Warp Cooldown": 120,
        "Fuel/AU Warped": 36.97,
        "Fuel/AU Subwarp": 28.44,
        "Fuel (Asteroid Exit)": 10,
        "Scan Cooldown (sec)": 54,
        "Active Crew (For Crafting)": 2,
        "Respawn Time (s)": 80,
        "Toolkits/Scan": 2,
        "Crew (For Food Cons)": 2,
    },
    {
        Symbol: "VZUSAM",
        Model: "AMBWE",
        Manufacturer: "VZUS",
        Spec: "Bounty Hunter",
        Class: 3,
        "Cargo Capacity": 4180,
        "Fuel Capacity": 4313,
        "Ammo Capacity": 4645,
        "Food/s (Mining)": 0.062,
        "Ammo/s (Mining)": 0.213,
        "Mining Rate (Resource/s)": 4.256,
        "Subwarp Speed (AU/s)": 0.0052,
        "Warp Speed (AU/s)": 0.1,
        "Max Warp Distance": 5.4,
        "Base Warp Cooldown": 180,
        "Fuel/AU Warped": 138.97,
        "Fuel/AU Subwarp": 106.9,
        "Fuel (Asteroid Exit)": 38,
        "Scan Cooldown (sec)": 42,
        "Active Crew (For Crafting)": 3,
        "Respawn Time (s)": 121,
        "Toolkits/Scan": 3,
        "Crew (For Food Cons)": 3,
    },
    {
        Symbol: "CHI",
        Model: "CHI",
        Manufacturer: "Rainbow",
        Spec: "Fighter",
        Class: 3,
        "Cargo Capacity": 3832,
        "Fuel Capacity": 4023,
        "Ammo Capacity": 4396,
        "Food/s (Mining)": 0.021,
        "Ammo/s (Mining)": 0.219,
        "Mining Rate (Resource/s)": 4.375,
        "Subwarp Speed (AU/s)": 0.0073,
        "Warp Speed (AU/s)": 0.1,
        "Max Warp Distance": 5.85,
        "Base Warp Cooldown": 180,
        "Fuel/AU Warped": 138.97,
        "Fuel/AU Subwarp": 106.9,
        "Fuel (Asteroid Exit)": 38,
        "Scan Cooldown (sec)": 55,
        "Active Crew (For Crafting)": 1,
        "Respawn Time (s)": 121,
        "Toolkits/Scan": 3,
        "Crew (For Food Cons)": 1,
    },
  
];

module.exports = shipData;
